# Generated by Django 4.2.5 on 2023-09-12 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0003_alter_ip_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='slug',
        ),
    ]
