# Generated by Django 4.2.5 on 2023-09-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0007_alter_ip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='status',
            field=models.CharField(choices=[('C', 'Close'), ('O', 'Open'), ('N', 'No data')], max_length=1),
        ),
    ]
