# Generated by Django 4.2.5 on 2023-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0008_alter_ip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='allow_ports',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ip',
            name='open_ports',
            field=models.CharField(default=1, max_length=70),
            preserve_default=False,
        ),
    ]
