# Generated by Django 4.2.5 on 2023-09-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0009_ip_allow_ports_ip_open_ports'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='status',
            field=models.CharField(max_length=7),
        ),
    ]
