# Generated by Django 4.2.5 on 2023-09-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0010_alter_ip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='update_time',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
