# Generated by Django 4.2.5 on 2023-09-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0011_ip_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='update_time',
            field=models.CharField(default='Не сканировался', max_length=20),
        ),
    ]
