# Generated by Django 4.2.5 on 2023-09-14 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0012_alter_ip_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='scanning_now',
            field=models.BooleanField(default=False),
        ),
    ]
