# Generated by Django 4.2.5 on 2023-09-14 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0013_ip_scanning_now'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='scanning_now',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='update_time',
        ),
    ]
