# Generated by Django 4.2.5 on 2023-09-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0014_remove_ip_scanning_now_remove_ip_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='scanning_now',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip',
            name='update_time',
            field=models.CharField(default='Не сканировался', max_length=20),
        ),
    ]
